
alias scr="cd ~/.scripts/"
alias account="open -a libreoffice.app ~/Documents/work_and_gigs/studio/business_documents/Max_Spreadsheets_2022.ods; vim ~/Documents/work_and_gigs/studio/business_documents/money_deposit_checklist.txt"
alias apps="cd /Applications/; ls"
alias ashish="open -a safari https://www.youtube.com/c/AshishXiangyiKumar"
alias cblind='bash ~/.scripts/colorblind.sh'
alias codedir="cd ~/documents/the_vault/code/"
alias comp="bash ~/.scripts/composition.sh"
alias doccopy="bash /Volumes/T7/.scripts/max_copy_script.sh"
alias edali="vim ~/.bash_aliases"
alias edbash="vim ~/.bash_profile"
alias edz="vim ~/.zshrc"
alias finder="open -a finder ."
alias findn="find ~ -type d -name"
alias fri="open ~/documents/the_vault/daily_checklists/friday_checklist.pages"
alias gacp="git add .; git commit; git push"
alias gmail="open -a safari https://mail.google.com/mail/u/o/#inbox"
alias hgit='bash ~/.scripts/hgit.sh'
alias how_many="python3 ~/documents/the_vault/code/days_till_graduation.py"
alias izzy="cd ~/Documents/work_and_gigs/izzy_burns ; ls"
alias izzytd="vim ~/Documents/work_and_gigs/izzy_burns/todo.txt"
alias jake='bash ~/.scripts/jake.sh'
alias jup="jupyter notebook"
alias kitchen='open ~/documents/the_vault/daily_checklists/kitchen_checklist.pages'
alias lib="open -a safari https://cmu.marmot.org"
alias live="open -a 'Ableton Live 11 Standard.app'"
alias met="open ~/Documents/the_vault/metronomes\ Project/metronomes.als"
alias miranda="bash ~/.scripts/miranda.sh"
alias mon="open ~/documents/the_vault/daily_checklists/monday_checklist.pages"
alias mvdisk="bash ~/documents/the_vault/code/disk_images/disk_image_copy_script.sh"
alias owlmla="open -a safari https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_formatting_and_style_guide.html"
alias pakc="open ~/documents/the_vault/travel/packing_list.pages"
alias pno='open ~/Music/Ableton/"User Library"/Templates/piano.als'
alias prnt="open -a safari https://goprint.coloradomesa.edu:7773/user/signin.jsp"
alias ra="cd ~/Documents/work_and_gigs/ra_lasater; ls"
alias racks='open ~/Music/Ableton/"User Library"/Templates/all_racks_1.0.als'
alias racksed='open ~/documents/the_vault/racks_project/racks.als'
alias ragit='bash ~/.scripts/ragit.sh'
alias ramv="cp ~/Documents/work_and_gigs/ra_lasater/**/**.pdf ~/Documents/work_and_gigs/ra_lasater/ipad/"
alias reflect="bash ~/.scripts/reflection.sh"
alias reflection="nano ~/documents/academic_documents/CMU/senior_recital/documentation/lesson_reflection.txt"
alias rowret='python3 ~/documents/the_vault/code/tone_row.py'
alias run='open ~/documents/the_vault/daily_checklists/daily_run.pages'
alias safari="open -a safari"
alias sbash="source ~/.bash_profile"
alias scec="open ~/documents/work_and_gigs/swing_city_express/swing_city_express_checklists.pages"
alias scram='open ~/documents/the_vault/daily_checklists/scrambled_eggs.pages'
alias snek="python3 ~/documents/the_vault/Code/games/snake.py"
alias spacerace="bash ~/documents/the_vault/code.scripts/spacerace.sh"
alias stretch="open ~/documents/the_vault/logic/stretch_timer/Bounces/stretch_timer.mp3"
alias sz="source ~/.zshrc"
alias tcrcite="open ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/citations.odt"
alias tcre2="cd ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/; pwd"
alias tcressay="open ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/essay_no.2.odt"
alias tcrout="open ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/essay_outline.odt"
alias tcrrn="echo''; echo''; date >> ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/research_notebook.txt; nano ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/research_notebook.txt"
alias tcrru="open -a libreoffice ~/Documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/essay_no.2_prompt.odt" 
alias tcrtd="open ~/documents/academic_documents/CMU/taos_cultural_revolution/essay_no.2/essay_no.2_checklist.odt"
alias tcrwc="open ~/documents/academic_documents/CMU/taos_cultural_revolution/midterm/midterm_works_cited.odt"
alias thurs="open ~/documents/the_vault/daily_checklists/thursday_checklist.pages"
alias transcribe="open ~/Music/Ableton/'User Library'/Templates/transcription_template_1.0.als; open -a '4k Video Downloader.app'"
alias tues="open ~/documents/the_vault/daily_checklists/tuesday_checklist.pages"
alias vsali="code ~/.bash_aliases"
alias wcjoc="open ~/documents/work_and_gigs/wcjo/wcjo_checklists.pages"
# project links
source ~/Documents/work_and_gigs/ra_lasater/.bash_scripts/.project_aliases
source ~/Documents/the_vault/Church_Music/compositions/.bash_aliases
