

alias account="bash ~/.scripts/account.sh"
alias apps="cd /Applications/; ls"
alias cblind='bash ~/.scripts/colorblind.sh'
alias check="cd ~/Documents/the_vault/daily_checklists; ls"
alias codedir="cd ~/documents/the_vault/code/"
alias comp="bash ~/.scripts/composition.sh"
alias correspond="open ~/Documents/the_vault/daily_checklists/latex/correspondence_checklist.pdf"
alias deep="cd ~/Documents/the_vault/DeepBach; ls"
alias doccopy="bash /Volumes/T7/.scripts/max_copy_script.sh"
alias edali="vim ~/.bash_aliases"
alias edbash="vim ~/.bash_profile"
alias edvim="vim ~/.vimrc"
alias edz="vim ~/.zshrc"
alias finder="open -a finder ."
alias findn="find ~ -type d -name"
alias fri="open ~/documents/the_vault/daily_checklists/friday_checklist.pages"
alias gacp="git add .; git commit; git push"
alias gd="cd ~/Documents/work_and_gigs/cmu_music_theater/guys_and_dolls/; ls"
alias gfc="cd ~/Documents/work_and_gigs/studio/github_for_composers.github.io/; ls"
alias gmail="open -a safari https://mail.google.com/mail/u/o/#inbox"
alias hgit='bash ~/.scripts/hgit.sh'
alias izzy="cd ~/Documents/work_and_gigs/izzy_burns ; ls"
alias izzyset="code ~/Documents/work_and_gigs/izzy_burns/setlist.txt"
alias izzytd="vim ~/Documents/work_and_gigs/izzy_burns/todo.txt"
alias jake='bash ~/.scripts/jake.sh'
alias jup="jupyter notebook"
alias kitchen='open ~/documents/the_vault/daily_checklists/kitchen_checklist.pages'
alias live="open -a 'Ableton Live 11 Standard.app'"
alias load?="ls ~/Downloads/"
alias machine='cd ~/Documents/the_vault/umesh/the_machine_learning_journey.github.io/; ls'
alias met="open ~/Documents/the_vault/metronomes\ Project/metronomes.als"
alias miranda="bash ~/.scripts/miranda.sh"
alias mon="open ~/documents/the_vault/daily_checklists/monday_checklist.pages"
alias mvdisk="bash ~/documents/the_vault/code/disk_images/disk_image_copy_script.sh"
alias pakc="open ~/documents/the_vault/travel/packing_list.pages"
alias pno='open ~/Music/Ableton/"User Library"/Templates/piano.als'
alias prnt="open -a safari https://goprint.coloradomesa.edu:7773/user/signin.jsp"
alias prob="vim ~/Documents/the_vault/problems/problems.md"
alias ra="cd ~/Documents/work_and_gigs/ra_lasater; ls"
alias racks='open ~/Music/Ableton/"User Library"/Templates/all_racks_1.0.als'
alias racksed='open ~/documents/the_vault/racks_project/racks.als'
alias ragit='bash ~/.scripts/ragit.sh'
alias ramv="cp ~/Documents/work_and_gigs/ra_lasater/**/**.pdf ~/Documents/work_and_gigs/ra_lasater/ipad/"
alias reflect="bash ~/.scripts/reflection.sh"
alias reflection="nano ~/documents/academic_documents/CMU/senior_recital/documentation/lesson_reflection.txt"
alias rowret='python3 ~/documents/the_vault/code/tone_row.py'
alias run='open ~/documents/the_vault/daily_checklists/daily_run.pages'
alias safari="open -a safari"
alias sbash="source ~/.bash_profile"
alias scase="rename -f 'y/A-Z/a-z/' * ; rename -f 'y/ /_/' *"
alias scec="open ~/documents/work_and_gigs/swing_city_express/swing_city_express_checklists.pages"
alias scr="cd ~/.scripts/"
alias scram='open ~/documents/the_vault/daily_checklists/scrambled_eggs.pages'
alias search="sh ~/.scripts/search.sh"
alias shootc="open ~/Documents/guns_and_hunting/shooting_overnight_packing_list.odt"
alias snek="python3 ~/documents/the_vault/Code/games/snake.py"
alias stretch="open ~/documents/the_vault/logic/stretch_timer/Bounces/stretch_timer.mp3"
alias sz="source ~/.zshrc"
alias thea="cd ~/Documents/work_and_gigs/cmu_music_theater/; ls"
alias thurs="open ~/documents/the_vault/daily_checklists/thursday_checklist.pages"
alias tonmax="cd ~/Documents/the_vault/code/music/tone_row_maximalism/; ls"
alias tontd="vim ~/Documents/the_vault/code/music/tone_row_maximalism/README.md"
alias tonutil="python3 ~/Documents/the_vault/code/music/tone_row_maximalism/tone_row_utility/tone_row_utility.py"
alias transcribe="open ~/Music/Ableton/'User Library'/Templates/transcription_template_1.0.als; open -a '4k Video Downloader.app'"
alias treasure="cd ~/Documents/work_and_gigs/district_51/gjhs/22-23/drama/treasure_island/; ls"
alias treasuretd="vim ~/Documents/work_and_gigs/district_51/gjhs/22-23/drama/treasure_island/README.md"
alias tues="open ~/documents/the_vault/daily_checklists/tuesday_checklist.pages"
alias vsali="code ~/.bash_aliases"
alias wcjoc="open ~/documents/work_and_gigs/wcjo/wcjo_checklists.pages"
source ~/Documents/the_vault/Church_Music/compositions/.bash_aliases
source ~/Documents/work_and_gigs/ra_lasater/.bash_scripts/.project_aliases
